# Generated by Django 3.1.6 on 2021-02-06 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0002_criminallocation_file_policeprofile_suspected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+?(88)01[3-9][0-9]{8}$')], verbose_name='Mobile phone'),
        ),
    ]
